# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d7656e9525c97636f99841e65bcff93a824867f43c13c8a3baffac1a9979dddf53ca3f61f8d4becd2248b51fef31f2c6ffddd6e8a296dcbe50924cf38dd6a4

test:
  secret_key_base: b62d27a63cc203c679a12ed180450d1f98b028d3ce1bda51f06e2a8543ade617a601deebe023512b9ceb42bb3d02cad25a4578f4ea5cd5f279409d13e7b286de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { SecureRandom.hex(64) } %>
  <% if ENV.has_key?("DOTLEDGER_USERNAME") && ENV.has_key?("DOTLEDGER_PASSWORD") %>
  authentication:
    credentials:
      - username: <%= ENV["DOTLEDGER_USERNAME"] %>
        password: <%= ENV["DOTLEDGER_PASSWORD"] %>
  <% end %>
